baseURL = 'https://lympany.art/'
languageCode = 'en-us'
title = 'Art by Steve Lympany'
theme = ["github.com/onweru/newsroom"]
enableEmoji = true

[pagination]
disableAliases = false
pagerSize = 100
path = 'page'

paginate = 100
